import { useEffect, useRef, useState } from 'react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import api from '../../hooks/useApi';
import { formatCurrency } from '../../utils/formatCurrency';
import { StatusBadge } from '../../components/ui/StatusBadge';
import { useAuth } from '../../hooks/useAuth';
import { NbslLogo } from '../../components/ui/NbslLogo';

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

interface ExpenditureRequest {
  id: string;
  title: string;
  totalAmount: number;
  status: string;
  date: string;
  requester: { fullName: string };
}

interface ExpenditureData {
  year: number;
  grandTotal: number;
  monthlyTotals: { month: number; total: number }[];
  requests: ExpenditureRequest[];
}

// ── Print view (only visible when printing) ───────────────────────────────────
function PrintView({ data, year, role }: { data: ExpenditureData; year: number; role: string }) {
  const generatedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const topMonth = [...(data.monthlyTotals ?? [])].sort((a, b) => b.total - a.total)[0];
  const monthsWithSpend = data.monthlyTotals.filter((m) => m.total > 0).length;

  return (
    <div className="print-only">
      {/* ── Page 1: Summary ────────────────────────────────────── */}
      <div className="print-page">
        {/* Header */}
        <div className="print-header">
          <div className="flex items-center gap-3 mb-1">
            <NbslLogo size={36} color="#1d4ed8" />
            <div>
              <div className="text-lg font-bold text-gray-900">NDBSL — Nondestructive Biosensing Laboratory</div>
              <div className="text-xs text-gray-500">Chungnam National University</div>
            </div>
          </div>
          <div className="border-t border-gray-300 mt-3 pt-3">
            <h1 className="text-2xl font-bold text-gray-900">Expenditure Report — {year}</h1>
            <p className="text-sm text-gray-500 mt-1">
              Generated by {role} · {generatedDate}
            </p>
          </div>
        </div>

        {/* Key metrics */}
        <div className="print-metrics">
          <div className="print-metric-card">
            <div className="print-metric-label">Total Expenditure</div>
            <div className="print-metric-value">{formatCurrency(data.grandTotal)}</div>
          </div>
          <div className="print-metric-card">
            <div className="print-metric-label">Total Requests</div>
            <div className="print-metric-value">{data.requests.length}</div>
          </div>
          <div className="print-metric-card">
            <div className="print-metric-label">Active Months</div>
            <div className="print-metric-value">{monthsWithSpend} / 12</div>
          </div>
          <div className="print-metric-card">
            <div className="print-metric-label">Peak Month</div>
            <div className="print-metric-value">
              {topMonth ? MONTHS[topMonth.month - 1] : '—'}
            </div>
            {topMonth && (
              <div className="print-metric-sub">{formatCurrency(topMonth.total)}</div>
            )}
          </div>
        </div>

        {/* Monthly bar chart (text-based for print) */}
        <div className="print-section">
          <h2 className="print-section-title">Monthly Breakdown</h2>
          <table className="print-table">
            <thead>
              <tr>
                <th className="text-left">Month</th>
                <th className="text-right">Amount</th>
                <th className="text-right">% of Total</th>
              </tr>
            </thead>
            <tbody>
              {MONTHS.map((name, i) => {
                const monthData = data.monthlyTotals.find((m) => m.month === i + 1);
                const amount = monthData?.total ?? 0;
                const pct = data.grandTotal > 0 ? ((amount / data.grandTotal) * 100).toFixed(1) : '0.0';
                return (
                  <tr key={i} className={amount > 0 ? 'font-medium' : 'text-gray-400'}>
                    <td>{name}</td>
                    <td className="text-right">{amount > 0 ? formatCurrency(amount) : '—'}</td>
                    <td className="text-right">{amount > 0 ? `${pct}%` : '—'}</td>
                  </tr>
                );
              })}
              <tr className="print-total-row">
                <td>Total</td>
                <td className="text-right">{formatCurrency(data.grandTotal)}</td>
                <td className="text-right">100%</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="print-footer">NDBSL Lab Management System · Confidential</div>
      </div>

      {/* ── Page 2+: Detailed requests ─────────────────────────── */}
      <div className="print-page print-page-break">
        <div className="print-header">
          <div className="flex items-center gap-3 mb-3">
            <NbslLogo size={24} color="#1d4ed8" />
            <span className="font-bold text-gray-900 text-sm">NDBSL Expenditure Report {year} — Request Details</span>
          </div>
          <div className="border-t border-gray-200" />
        </div>

        <div className="print-section">
          <table className="print-table">
            <thead>
              <tr>
                <th className="text-left" style={{ width: '40%' }}>Request Title</th>
                <th className="text-left">Requester</th>
                <th className="text-left">Date</th>
                <th className="text-left">Status</th>
                <th className="text-right">Amount</th>
              </tr>
            </thead>
            <tbody>
              {data.requests.map((r) => (
                <tr key={r.id}>
                  <td className="font-medium">{r.title}</td>
                  <td>{r.requester.fullName}</td>
                  <td>{new Date(r.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</td>
                  <td className="capitalize">{r.status}</td>
                  <td className="text-right font-medium">{formatCurrency(r.totalAmount)}</td>
                </tr>
              ))}
            </tbody>
            <tfoot>
              <tr className="print-total-row">
                <td colSpan={4}>Grand Total</td>
                <td className="text-right">{formatCurrency(data.grandTotal)}</td>
              </tr>
            </tfoot>
          </table>
        </div>

        <div className="print-footer">NDBSL Lab Management System · Confidential · Page 2</div>
      </div>
    </div>
  );
}

// ── Main component ────────────────────────────────────────────────────────────
export default function Expenditure() {
  const { user } = useAuth();
  const currentYear = new Date().getFullYear();
  const [year, setYear] = useState(currentYear);
  const [data, setData] = useState<ExpenditureData | null>(null);
  const [loading, setLoading] = useState(true);
  const printRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    setLoading(true);
    api.get(`/api/expenditure?year=${year}`)
      .then((r) => setData(r.data))
      .finally(() => setLoading(false));
  }, [year]);

  const chartData = data?.monthlyTotals.map((m) => ({
    name: MONTHS[m.month - 1],
    total: m.total,
  })) ?? [];

  const handlePrint = () => {
    window.print();
  };

  return (
    <div>
      {/* ── Print CSS injected into document ── */}
      <style>{`
        @media print {
          /* Hide sidebar and screen UI; show only the print content */
          aside { display: none !important; }
          main { margin-left: 0 !important; padding: 0 !important; overflow: visible !important; }
          .no-print { display: none !important; }
          .print-only { display: block !important; }
          .print-page {
            page-break-after: always;
            padding: 18mm 16mm;
            font-size: 11px;
          }
          .print-page-break { page-break-before: always; }
          .print-header { margin-bottom: 16px; }
          .print-metrics {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 10px;
            margin-bottom: 20px;
          }
          .print-metric-card {
            border: 1px solid #e5e7eb;
            border-radius: 6px;
            padding: 10px;
          }
          .print-metric-label { font-size: 9px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.04em; }
          .print-metric-value { font-size: 18px; font-weight: 700; color: #111827; margin-top: 3px; }
          .print-metric-sub { font-size: 10px; color: #6b7280; margin-top: 2px; }
          .print-section { margin-bottom: 20px; }
          .print-section-title { font-size: 12px; font-weight: 600; color: #374151; margin-bottom: 8px; border-bottom: 1px solid #e5e7eb; padding-bottom: 5px; }
          .print-table { width: 100%; border-collapse: collapse; font-size: 10px; }
          .print-table th { background: #f9fafb; padding: 7px 9px; font-size: 9px; font-weight: 600; color: #6b7280; text-transform: uppercase; border-top: 1px solid #e5e7eb; border-bottom: 1px solid #e5e7eb; }
          .print-table td { padding: 6px 9px; border-bottom: 1px solid #f3f4f6; color: #374151; }
          .print-total-row td { font-weight: 700; border-top: 2px solid #d1d5db; background: #f9fafb; padding-top: 8px; }
          .print-footer { margin-top: 24px; font-size: 8px; color: #9ca3af; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 6px; }
        }
        @media screen {
          .print-only { display: none; }
        }
      `}</style>

      {/* ── Screen UI ── */}
      <div className="no-print">
        <div className="flex items-center justify-between mb-6">
          <h1 className="text-2xl font-bold text-gray-900">Expenditure Report</h1>
          <div className="flex items-center gap-3">
            <select
              value={year}
              onChange={(e) => setYear(parseInt(e.target.value))}
              className="border border-gray-300 rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary-500"
            >
              {Array.from({ length: 5 }, (_, i) => currentYear - 2 + i).map((y) => (
                <option key={y} value={y}>{y}</option>
              ))}
            </select>
            {data && (
              <button
                onClick={handlePrint}
                className="flex items-center gap-2 bg-primary-600 hover:bg-primary-700 text-white px-4 py-2 rounded-md text-sm font-medium transition-colors"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
                </svg>
                Print Report
              </button>
            )}
          </div>
        </div>

        {loading ? (
          <div className="text-gray-400 text-sm animate-pulse">Loading…</div>
        ) : (
          <>
            <div className="bg-white rounded-lg border border-gray-200 p-6 mb-6">
              <div className="flex items-center justify-between mb-4">
                <h2 className="font-semibold text-gray-800">Monthly Expenditure — {year}</h2>
                <span className="text-lg font-bold text-gray-900">Total: {formatCurrency(data?.grandTotal ?? 0)}</span>
              </div>
              <ResponsiveContainer width="100%" height={280}>
                <BarChart data={chartData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="name" tick={{ fontSize: 12 }} />
                  <YAxis tickFormatter={(v) => `₩${(v / 1000).toFixed(0)}k`} tick={{ fontSize: 12 }} />
                  <Tooltip formatter={(v: number) => formatCurrency(v)} />
                  <Bar dataKey="total" fill="#2563eb" radius={[3, 3, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>

            <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">
              <table className="w-full text-sm">
                <thead className="bg-gray-50 border-b border-gray-200">
                  <tr>
                    <th className="text-left px-4 py-3 text-xs font-medium text-gray-500">Title</th>
                    <th className="text-left px-4 py-3 text-xs font-medium text-gray-500">Requester</th>
                    <th className="text-left px-4 py-3 text-xs font-medium text-gray-500">Date</th>
                    <th className="text-left px-4 py-3 text-xs font-medium text-gray-500">Status</th>
                    <th className="text-right px-4 py-3 text-xs font-medium text-gray-500">Amount</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-100">
                  {(data?.requests ?? []).map((r) => (
                    <tr key={r.id} className="hover:bg-gray-50">
                      <td className="px-4 py-3 font-medium text-gray-900">{r.title}</td>
                      <td className="px-4 py-3 text-gray-600">{r.requester.fullName}</td>
                      <td className="px-4 py-3 text-gray-600">
                        {new Date(r.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                      </td>
                      <td className="px-4 py-3"><StatusBadge status={r.status} /></td>
                      <td className="px-4 py-3 text-right font-medium">{formatCurrency(r.totalAmount)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </>
        )}
      </div>

      {/* ── Print-only view (hidden on screen, shown when printing) ── */}
      {data && (
        <div ref={printRef}>
          <PrintView data={data} year={year} role={user?.role ?? 'user'} />
        </div>
      )}
    </div>
  );
}
